### ISSUE TITLE
[feature] allow to adjust historical records to a fixed date/time

### ISSUE THREAD

**Issue by svenXY** [GothenburgBitFactory/timewarrior#131]
Hi,

it would be nice if one could adjust the start or end time of a historical record to a fixed date/time, like e.g.

```bash
timew ended @1 23:00
timew started @1 11:30
```

Very often, I can more or less remember when I switched to a different task, but then having to calculate how much I have to lengthen or shorten or whatever is very time-consuming

**Comment by lauft** [comment]
I like the idea, but I would alter the command to 
```
timew modify (start|end) <id> <date>
```
This is more in the style "TimeWarrior do <foo>" like the other commands - plus one could integrate shorten and lengthen
```
timew modify length <id> (|+|-)<duration>
```

**Comment by svenXY** [comment]
sounds good to me.

**Comment by sruffell** [comment]
I also like @lauft's proposed syntax. I wonder if anyone does not like it?  I hit this enough that I probably should write my own pull request to add this feature.

**Comment by sruffell** [comment]
Just a heads up, that I've also pushed a branch to my fork of timewarrior that has this change applied against the 1.1.1 branch so I can start using it without modifying the format of the database.  When I tried to run with the branch based off dev, I ran into problems since the tags database wasn't updated and there isn't a 'standard' way to migrate yet, like as proposed in #182.

So anyone who is interested can use the commit at the tip of the branch below with their current database:
https://github.com/sruffell/timewarrior/tree/modify_cmd_1.1.1

**Comment by sorsasampo** [comment]
@lauft anything stopping @sruffell's commits from being merged?

I think this feature is important enough to warrant a new release by itself. It's one of the things I miss most from [samg/timetrap](https://github.com/samg/timetrap).
