### ISSUE TITLE
trying to track something that would be before epoch fails silently, corrupting database

### ISSUE THREAD

**Issue by nodens** [GothenburgBitFactory/timewarrior#290]
Hi,

I was testing some notation for  #289 when I ran into the following issue:

```
~$ timew track 1h after 1970-01-01T00:00 test
~$ echo $?
0
~$ timew export
'19691231T230000Z' is not a valid date in the '' format.
~$ timew start
'19691231T230000Z' is not a valid date in the '' format.
~$ cat .timewarrior/data/1970-01.data 
inc 19691231T230000Z # test
nodens@shadowfax:~$ rm -f .timewarrior/data/1970-01.data
nodens@shadowfax:~$ timew track 1.5h after 1970-01-02T00:00 test
Recorded test
  Started 1970-01-02T00:00:00
  Ended              01:30:00
  Total               1:30:00

```

In my current local time (UTC+0100), 1970-01-01T00:00 is indeed before epoch.
Such db entry is not parseable by timew, so you need to delete it before you can use the db again.

Cheers!

**Comment by sruffell** [comment]
The error you are seeing is because [libshared/Datetime](https://github.com/GothenburgBitFactory/libshared/blob/master/src/Datetime.cpp#L91-L92) is failing to parse the interval timestamp.  From looking at the parse code, it is not clear to me if it *should* allow dates before the epoch or not.

That said, it seems safe to assume that timewarrior should never write any interval to the database that cannot also be parsed. PR #290 should prevent you from needing to manually edit the database to get out of this situation.
