### ISSUE TITLE
please add hint :all or similar for "since the begining"

### ISSUE THREAD

**Issue by nodens** [GothenburgBitFactory/timewarrior#296]
Hi,

It would be convenient to have a way to get a summary from all time, like export does but readable by a human.

Currently I use:
`timew summary 1970W01 - now`

but that's tedious to type ;)

Thanks!

**Comment by sruffell** [comment]
I find myself typing `:all` quiet frequently, even though it never works.

**Comment by ahillio** [comment]
This is a truly essential function.  I'm surprised it's not provided by timewarrior out-of-the-box.

It's achievable via a custom extension @lauft provided as an example so that `timew all` and `timew all myTag` can work...

First do `pip install timew-report` to get the utilities....

Then place the following code into a file called `all` located in `.timewarrior/extensions` (type command `timew extensions` to ensure you have the correct extension directory)...

```
vi .timewarrior/extensions/all
#then paste the following text into the file:
#!/usr/bin/python
import sys
from timewreport.parser import TimeWarriorParser

parser = TimeWarriorParser(sys.stdin)

totals = dict()

for interval in parser.get_intervals():
    tracked = interval.get_duration()
    
    for tag in interval.get_tags():
        if tag in totals:
            totals[tag] += tracked
        else:
            totals[tag] = tracked

# Determine largest tag width.
max_width = len('Total')

for tag in totals:
    if len(tag) > max_width:
        max_width = len(tag)

# Compose report header.
print('Total by Tag')
print('')

# Compose table header.
print('{:{width}} {:>10}'.format('Tag', 'Total', width=max_width))
print('{} {}'.format('-' * max_width, '----------'))

# Compose table rows.
grand_total = 0
for tag in sorted(totals):
    formatted = totals[tag].seconds
    grand_total += totals[tag].seconds
    print('{:{width}} {:10}'.format(tag, formatted, width=max_width))

# Compose total.
print('{} {}'.format(' ' * max_width, '----------'))
print('{:{width}} {:10}'.format('Total', grand_total, width=max_width))

# then save and quite
# then make executable:
chmod +x .timewarrior/extensions/all
```

Though I'm a little confused by why when doing `timew all myTag` I'm getting multiple instances of tracked time added up together... so for my testing here....

```
 timew all "Test Client"                                       INSERT  ✔  780  18:08:40
Total by Tag

Tag              Total
----------- ----------
Test Client        112
clients            112
test               112
            ----------
Total              336
```
"Test Client" is a "task" (in taskwarrior, which apparently just gets transformed to a "tag" in timewarrior) that has "clients" and "test" as its two tags.  I'm surprised they get added up like this, but I'm grateful for this starting point and a step in the right direction.

**Comment by lauft** [comment]
Duplicates #206

**Comment by lauft** [comment]
I am closing this as a duplicate. Please continue any discussion in #206.
