### ISSUE TITLE
unicode input causes indefinite hang for commands like day or month

### ISSUE THREAD

**Issue by sclee15** [GothenburgBitFactory/timewarrior#309]
Reproduce steps
add one line to 2020-04.data
inc 20200429T210849Z - 20200429T212340Z # "성경 3장 읽기"
and timew day.

It hangs on my machine and consumes ram so much.
Thank you for maintaining TW it changed the way I log time.

**Comment by sruffell** [comment]
The hang / memory consumption is due to a bug in libshared's [wrapText](https://github.com/GothenburgBitFactory/libshared/blob/0d4e31de757ea2609/src/shared.cpp#L46-L56)

It would be best to make wrapText / extractText width be the count of characters on the screen (and not a byte width), but timewarrior could work around it with something like below. This will only show the tag if the utf8 character width is within the width (and it won't try to wrap), but otherwise functions normally for text where the utf-8 width matches the byte length of the label.

```diff
diff --git a/src/Chart.cpp b/src/Chart.cpp
index b6b2830..ad0a56d 100644
--- a/src/Chart.cpp
+++ b/src/Chart.cpp
@@ -35,6 +35,7 @@
 #include <cassert>
 #include <timew.h>
 #include <Chart.h>
+#include <utf8.h>

 ////////////////////////////////////////////////////////////////////////////////
 Chart::Chart (const ChartConfig& configuration) :
@@ -493,7 +494,16 @@ void Chart::renderInterval (
     if (width)
     {
       std::vector<std::string> text_lines;
-      wrapText (text_lines, label, width, false);
+
+      size_t utf8_characters = utf8_text_width (label);
+      if (static_cast <size_t>(width) >= utf8_characters)
+      {
+        text_lines.push_back (label);
+      }
+      else if (utf8_characters == label.size ())
+      {
+        wrapText (text_lines, label, width, false);
+      }

       for (unsigned int i = 0; i < lines.size (); ++i)
       {
```


The following script will setup the database to reliably recreate the error:
```python
#!/usr/bin/env python3

import subprocess
from datetime import datetime

now = datetime.now()
start = "{0:02d}:30:00".format(now.hour - 4)
end = "{0:02d}:00:00".format (now.hour)
subprocess.call(["timew", "track", start, "-", end, u'안녕하세요 월드'])
```

**Comment by sruffell** [comment]
@lauft Given that this issue can allow the OOM killer to run on Linux, I believe it should be added to the 1.4.0 milestone.

**Comment by lauft** [comment]
@sruffell Agreed

**Comment by lauft** [comment]
@sruffell I implemented your fix and opened respective issues in https://github.com/GothenburgBitFactory/libshared
