### ISSUE TITLE
Should track allow tracking time in the future?

### ISSUE THREAD

**Issue by sruffell** [GothenburgBitFactory/timewarrior#350]
While thinking about #332, one idea that might prevent that is if times in the future should be valid.  Currently, the track command does allow tracking time in the future, but I'm wondering if that is intentional or an oversight.

For example:

```shell
$ rm -fr ~/.timewarrior
$ src/timew track :yes tomorrow project-tomorrow
Note: '"project-tomorrow"' is a new tag.
Recorded "project-tomorrow"
  Started 2020-07-25T00:00:00
  Ended           26T00:00:00
  Total              24:00:00
$ src/timew start 8am
You cannot overlap intervals. Correct the start/end time, or specify the :adjust hint.
$ src/timew
There is no active time tracking.
$ src/timew summary
No filtered data found in the range 2020-07-24T00:00:00 - 2020-07-25T00:00:00.
```

**Comment by lauft** [comment]
This is rather intentional, as one usually does not track times in the future. The rule has been weakened such that it is possible to stop intervals in the future, but currently you cannot start them in the future.

One could abolish the restriction all together, but then there will still be the issue that an open interval will *always* overlap with future intervals and trigger the related error messages.

**Comment by sruffell** [comment]
Perhaps I'm confused. It seems that the current behavior is to allow tracking in the future?

So a change to prevent starting an interval in the future would be welcome?  This would also simplify #332 since a user shouldn't have been able to track time in the future anyway, so it is safe to assume that a future time is really for the previous day.

**Comment by lauft** [comment]
I think there are some cases where future time tracking could be allowed. So I would argue against a general rule against it.

One case that comes into my mind from my own experience is when you need to track your paid holidays and have to turn in your timesheet while on holiday. So at least it should be possible to add future intervals with `track` to complete your timesheet to turn it in. In this case I would accept that as soon as I entered a future interval I can no longer start intervals before that, because Timewarrior detects an overlap.

Another case that should be (and already is) supported is when you want to finish your work, but still need to do some "cleanup" (put your things together, grab your stuff...). Of course you can pack your laptop, do the cleanup and remember the time when you finished with all this and enter it the next time you use Timewarrior. But often you know your ramp-down time, so you can enter it in advance and finish your job accordingly (if you need to catch a train/plane I bet this becomes more than precise...).

The latter one collides a bit with the situation described by @xerus2000 in #332. Here we have the special case of an interval crossing midnight (should I worry? :wink:) where backdating is more reasonable than assuming a future time. In my example backdating would also result in an invalid interval, because its end time is most likely before its start time then.

I think Timewarrior should not prevent tracking in the future, but when dealing with ambiguous datetimes it should always pick the one in the past. That means when an interval is started at 17:00 and stopped at 17:40 with 17:45, it should accept this future date (because backdating would create an invalid interval). When starting an interval at yesterday 22:00 and stopping it at 1:00 with 23:30, it should backdate it as it will produce an valid interval. However a fully specified datetime should always override this.

**Comment by sruffell** [comment]
👍 This sounds good to me.
