### ISSUE TITLE
timew track in the future causing overlap in the present

### ISSUE THREAD

**Issue by qdii** [GothenburgBitFactory/timewarrior#402]
Let's say I have a few meetings today that I would like to account for, so that I know how many hours I should work to reach my daily quota. I first run `timew track 11:00 - 12:00 meeting`, then I try to start tracking my current task with `timew start work`, but I get the error message:

> You cannot overlap intervals. Correct the start/end time, or specify the :adjust hint.

Since it's 8AM, there is no overlap, so the expected behavior would be for time to start being tracked

**Comment by lauft** [comment]
Starting time tracking creates an open interval, in your case von from `[8:00 - ∞)`,  so there is an overlap!

By design, Timewarrior is a time *tracking* tool, not a time *planning* tool. 

Yes, Timewarrior allows to enter future timestamps, but those are intended for use cases like
* you are about to pack up work and do not want to be your time tracking be the very last thing to do. So you enter a future end time for your current task.
* you are hosting a meeting and do not want your time tracking get in the way of greeting your participants. So you enter a future start time and are ready then.
* you need to submit your timesheet in advance because you are on holiday at the end of month and accounting needs your data including your time off. So you track your future time off intervals while not having active time tracking.

Your use case is better solved by a Timewarrior extension, which accumulates your current work time and compares it to a defined budget.
