### ISSUE TITLE
What about an html-based overview of "timew summary" ?

### ISSUE THREAD

**Issue by justUmen** [GothenburgBitFactory/timewarrior#418]
I have been using timewarrior to trackdown my behavior on my laptop on a 30 seconds basis.
To really track down how much time I'm away from keyboard, when my laptop is in sleep mode, how much time i spend on youtube, on text editor, etc..
But with my tracking on a 30 seconds basis the result of `timew day` doesn't really tell me much.

Is there a way to have a more detailed version (maybe 1 hour/line instead of 24h), maybe in an interactive html webpage.

I was about to start doing that with some parsing of the `timew summary` results, but I thought I should check it there before, if someone already did something similar.

**Comment by lauft** [comment]
@justUmen You can use `timew report <your_report> :day` which exports all your intervals of the given range (here, the current day) as a JSON array, along with meta information. See https://timewarrior.net/docs/api/ for more information on that.
`<your_report>` then would consume this information and produce the webpage from it. If you want to do it in Python, you can use e.g. the package [timew-report](https://pypi.org/project/timew-report/ ) as a basis for that.
Otherwise, the webpage has a section, where tools and extension for Timewarrior are listed: https://timewarrior.net/tools/

**Comment by szszszsz** [comment]
> I have been using timewarrior to trackdown my behavior on my laptop on a 30 seconds basis.
> To really track down how much time I'm away from keyboard, when my laptop is in sleep mode, how much time i spend on youtube, on text editor, etc..

@justUmen slightly offtopic, but would an automatic time tracker not suit better for this use case?
- https://activitywatch.net/

As for making the interactive page, how about D3?
- https://d3js.org/
