### ISSUE TITLE
Help Future date tracking causing issues.  

### ISSUE THREAD

**Issue by KingJulianS** [GothenburgBitFactory/timewarrior#504]
Hi, 

Sort of related to closed issue  #491. 
I captured a tracking date in the future, simply because I know the event will happen, like a day off etc…
` $timew track 2022-10-07T08:00:00 - 2022-10-07T17:00:00 day_off `

Now, whenever I use start to track something current, I get the following : 
`$ timew start XYZ<CR>`
`~ You cannot overlap intervals. Correct the start/end time, or specify the :adjust hint.`

It will only work once I deleted the future tracking. 

Is this by design ? If so, can it rather prevent future tracking in the first place or alternatively allow me to track current even though there is a future tracking already. i.e. Maybe it can check when I do $timew stop if it will overlap and give that message if so, but not on start since it is not overlapping yet.

**Comment by lauft** [comment]
Yes, this is by design. Timewarrior is a time _tracker_, not a _planner_. Therefore, support for future intervals is (and will be) limited.

When you start tracking, Timewarrior creates a half-open interval from your start date, which overlaps with any future interval present in the database. So when you enter a future interval, you can only track intervals before with a defined end date.

**Comment by KingJulianS** [comment]
Thanks
