### ISSUE TITLE
tags misplaced when cell width

### ISSUE THREAD

**Issue by champignoom** [GothenburgBitFactory/timewarrior#558]
This is what `timew day` looks like with an empty timewarrior.cfg:
![image](https://github.com/GothenburgBitFactory/timewarrior/assets/66909116/f3c04ffc-ac10-42f1-9701-fee36b937600)

But after adding the followings to timewarrior.cfg:
```
define reports:
  day:
    cell = 7
```
It becomes like this:
![image](https://github.com/GothenburgBitFactory/timewarrior/assets/66909116/f493dfb3-d337-4aa8-a679-0266cba0c156)

where both tags are shifted rightwards.

**Comment by champignoom** [comment]
version 1.5.0

**Comment by lauft** [comment]
@champignoom What are the start and end time of both intervals?

**Comment by champignoom** [comment]
@lauft it's 10:10:00-16:44:11 and 17:42:12-18:00:00 respectively

**Comment by lauft** [comment]
@champignoom The quick answer to your issue is given by `timew help chart` in the `CONFIGURATION` section. Here it says for `reports.<type>.cell`:
> ... Suitable values are the divisors of 60 ...

As `7` does not fit that rule, weird behavior is somewhat expected... 😅 
So, pick `6` instead.

I might try to figure out, what exactly is going haywire here, but I guess this is rather another point on the TODO list for config validation. 🤔

**Comment by champignoom** [comment]
Thanks, `10` fits my screen width and behaves well.
