### ISSUE TITLE
[TI-1] Add an 'undo' command

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/timewarrior#9]
_Paul Beckingham on 2016-04-08T12:30:48Z says:_ 

 Add an undo command, and the associated transaction log to provide the data.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-04-08T12:30:48Z
Modified: 2016-08-16T20:25:24Z
```

**Comment by lauft** [comment]
I am closing this ticket because of age. Currently there is no (urgent) need for an undo command. Corrections on intervals can be done with shorten/lengthen/move/...

**Comment by fcerbell** [comment]
My taskwarrior is connected to my TimeWarrior. I changed the scheme of my projects and tags in taskwarrior. I wanted to batch such a change in the history of timewarrior. Things went wrong. I was able to "undo" everything in my taskwarrior, but the undo command in timewarrior missed me. No other choice than restoring a backup. 
The undo command would really be useful in such situation. When a tag label change, it has to be updated in the past in all records.

Another usecase : 
I wanted to lengthen an interval by 30min but I lengthened it by 30m !!! then the mess occured and I had to manually edit the data files.

**Comment by lauft** [comment]
It is always difficult to rewrite history.

I am curious, how you batched your change in the history of timewarrior. Did you run a script with taskwarrior commands that did your changes and timewarrior followed along with the on-modify-hook script? Or did you do your taskwarrior and timewarrior modifications separately? What was the intended goal (in timewarrior)? Renaming an existing tag? Merging assigned tags?

> When a tag label change, it has to be updated in the past in all records.
When you have a tag "FOO" and you decide it should rather be called "BAR" then I agree. When you have an interval which carries label "FOO" and you change it to "BAR", I do not. And I am not sure whether this should happen automatically...

I think the last part is not directly liked to the undo command and more a feature request for timewarrior's tag command ("renaming existing tags").

Do you have a small example for your last usecase? I would have expected that if you have e.g. 2 intervals
```
09:00 - 10:00 FOO
11:00 - 12:00 BAR
```
lengthening "FOO" by <1h should work, but anything >1h should be cause an error because of the resulting overlap with "BAR".

**Comment by fcerbell** [comment]
Hi,

Well, I used a first script for taskwarrior such as :
for p in `task _projects`; do task pro:${p} modify pro:P.${p}; done
The idea is to prefix categories with the category letter T.xxx for
territories, C.xxx for contents (meeting, call, email, ...), ... to
better classify and filter tasks. Then tasks are pushed to timewarrior
with a on-modify hook.

Then, something similar in timewarrior :
for i in France Spain Portugal UK Belgium; do 
for t in `timew sum :id :year | grep -i "$i" | sed 's/.*\(@...\).*/\1/' | sort -u`; do
timew untag $t $i; timew tag $t C.$i;
done
done

My calendar is managed by remind (roaring penguin) and also
automatically pushes intervals in timewarrior. I try to remain
consistent with all theses tools to be able to extract useful statistics

I use an interractive script to pick the right tags from a static list
or a dynamic list (task projects, for exemple). 

Anytime, I might have to change my categories. Lets say that I use
Internal.Paperwork and Internal.Meeting projects in taskwarrior, they are
pushed as tags in timewarrior (no project there). Later, I have so many
distinct projects that I chose to merge these two projects as P.Internal
in taskwarrior. They will be pushed with a new tag in timewarrior and
Iit will be complex to get accurate stats from timewarrior...


Regarding the other issue, I am not using the lastest version (I prefer
to stick with Debian's stable packages). I was able to lengthen a task
later than "now". Even when this interval was stopped, it still was
incrementing in "timew sum" I was unable to "delete" it... 

Regards
François

Le samedi 21 avril 2018 à 06:39:37 (-0700), lauft a écrit :
> It is always difficult to rewrite history.
> 
> I am curious, how you batched your change in the history of timewarrior. Did you run a script with taskwarrior commands that did your changes and timewarrior followed along with the on-modify-hook script? Or did you do your taskwarrior and timewarrior modifications separately? What was the intended goal (in timewarrior)? Renaming an existing tag? Merging assigned tags?
> 
> > When a tag label change, it has to be updated in the past in all records.
> When you have a tag "FOO" and you decide it should rather be called "BAR" then I agree. When you have an interval which carries label "FOO" and you change it to "BAR", I do not. And I am not sure whether this should happen automatically...
> 
> I think the last part is not directly liked to the undo command and more a feature request for timewarrior's tag command ("renaming existing tags").
> 
> Do you have a small example for your last usecase? I would have expected that if you have e.g. 2 intervals
> ```
> 09:00 - 10:00 FOO
> 11:00 - 12:00 BAR
> ```
> lengthening "FOO" by <1h should work, but anything >1h should be cause an error because of the resulting overlap with "BAR".
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/GothenburgBitFactory/timewarrior/issues/9#issuecomment-383296316

-- 
François - 21 rue d'Eaubonne - 95580 Margency
Free : +33 6 03 01 55 12
http://www.cerbelle.net

**Comment by buc0** [comment]
I just made a mess of my time tracking when I went to insert a task that I forgot to track earlier in the day.  I started by adding the task with minimal time, moved it to the appropriate timeslot, then attempted to lengthen it by 10 minutes.

```timew``` complained that it would cause an overlap, and that I should use the ```:adjust``` hint to handle it automatically.  I looked and there was about a minute of overlap, so I just threw ```:adjust``` onto the command line.

What I diidn't realize, because I've just started using ```timew``` is that I had specified an interval of 10 *months*, and with the ```:adjust``` hint it happily proceeded to *remove* all of the intervals that conflicted.  Oops.

When I saw that there was a undo history file, and some references to an ```undo``` command in https://taskwarrior.org/docs/timewarrior/files.html I thought I was going to have a relatively easy time with it.  Sadly, no.

I guess I'm going to see if there's something I can work up external to ```timew``` to simulate an undo.

**Comment by ptonner** [comment]
Just want to second the issue raised by @buc0 - I have mistakenly clobbered a days worth (thankfully not months!) of time tracking 

given the presence of the backup data, it _would_ be useful to undo those changes

**Comment by fcerbell** [comment]
+1 the "m" for month is dangerous and confusing when you want to enter minutes (min) intervals. It was also one of the things that I wanted to "undo". This undo command would be really helpful to help adoption of timew. Everyone does mistakes while learning. If a mistake ruins hours of tracking during evaluation, you will not re-enter/fix the past, the stats will be inaccurate and this can be a show-stopper.

**Comment by lauft** [comment]
Agreed. I am reopening this issue.

**Comment by lauft** [comment]
First version of the 'undo' command implemented. Closes #9  TI-1

**Comment by michaellenahan** [comment]
Help! I made the mistake of typing "30m", which was interpreted as "30 months".
```
➜  ~ timew track 30m "Christopher - what to do in his absense with flimflam questions"
You cannot overlap intervals. Correct the start/end time, or specify the :adjust hint.
➜  ~ timew track 30m "Christopher - what to do in his absense with flimflam questions" :adjust
Recorded "Christopher - what to do in his absense with flimflam questions"
  Started 2016-12-10T10:24:46
  Ended   2019-05-29T11:24:46
  Total           21600:00:00
➜  ~ timew
Tracking DKRFTN "DKRFTN-2185 Disable dkr_exit_intent on live and deploy exported configuration changes"
  Started 2019-05-29T11:24:46
  Current                  48
  Total               0:00:02
```
I started using timewarrior (with taskwarrior and bugwarrior) about 3 weeks ago, loving it so far.
I can't find documentation on how to use the "undo" command in timewarrior.
I did find this, which looks very promising: https://www.dp.cx/blog/taskwarrior--timewarrior--and-that-moment-it-all-goes-wrong.html
... but I don't have monthly files, because I've only been using it in May 2019 so far.
The files I have in ~/.task/ are the following:
```
undo.data
backlog.data
pending.data
completed.data
```
Thanks!

**Comment by lauft** [comment]
Documentation on the `undo` command can be found here: [undo man page](https://github.com/GothenburgBitFactory/timewarrior/blob/dev/doc/man/timew-undo.1.in)
The command will be part of timewarrior 1.2.0

There is an issue for the problem with the 'm' duration prefix: #133
